# Generated by Django 6.0.7 on 2026-07-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_tutor_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tutor',
            managers=[
            ],
        ),
    ]
