# Generated by Django 6.0.7 on 2026-08-14 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
